name: Terraform Checks

on:
  workflow_dispatch: # because sometimes you just want to force a branch to have tests run
  pull_request:
    branches:
      - "**"
  merge_group:
    types:
      - checks_requested

defaults:
  run:
    working-directory: ./terraform

jobs:
  check-terraform-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.7.4
      - name: Terraform fmt
        run: terraform fmt -check -recursive

  check-terraform-validity:
    runs-on: ubuntu-latest
    env:
      TERRAFORM_DIRS: |
          implementation
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.7.4
      - name: Terraform Init
        run: |
          for d in $TERRAFORM_DIRS
          do
            echo "Initializing $d";
            (cd $d && terraform init -backend=false)
          done
      - name: Terraform Validate
        run: |
          for d in $TERRAFORM_DIRS
          do
            echo "Validating $d";
            (cd $d && terraform validate)
          done